### ISSUE TITLE
'podman images' fails with panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by steveb** [containers/libpod#1405]
/kind bug

**Description**

After doing a number of concurrent buildah builds, the storage is in a state where "podman images" fails

**Steps to reproduce the issue:**

1. Do a bunch of concurrent buildah builds (sorry, not very useful for reproducing)
2. run "podman --log-level=debug images"

**Describe the results you received:**
```
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] overlay: override_kernelcheck=true
DEBU[0000] overlay test mount with multiple lowers succeeded
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true
INFO[0000] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db
DEBU[0000] Set libpod namespace to ""
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@197877e78fd28ca0ac432584198ea94c6b5ef13b5135c572f9269360bbf27d3b"
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@0a8596ba75ac06792e9a133d1b2cb981d0a987e87de83f913604007cf2e8f66b"
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@bfc839866d1db4b4199ac44115a432aacd9b3299b9b81f95fec94c90c6d28fb4"
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@dd37bac25ad9881971834c03f9ec9d8e019a3a491a3947289b2735a970ae789e"
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@a6030d8550a2a92cc27ef223bfc1562e056bf3d4b870e285f72ef1bff3164801"
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@e48edeb3033196091cfbbb5dc068bd32a0814637f70d045a44e742390d2bcab8"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf532d9]

goroutine 1 [running]:
main.getImagesTemplateOutput(0x1354b80, 0xc4200340f0, 0xc4200ced10, 0xc420073c00, 0x12, 0x20, 0x0, 0x0, 0x0, 0xc4202d4400, ...)
        /builddir/build/BUILD/libpod-f38eb4fe50427549db8957e5033b73f04b4d5c82/_build/src/github.com/projectatomic/libpod/cmd/podman/images.go:295 +0x359
main.generateImagesOutput(0x1354b80, 0xc4200340f0, 0xc4200ced10, 0xc420073c00, 0x12, 0x20, 0x0, 0x0, 0x0, 0xc4202d4400, ...)
        /builddir/build/BUILD/libpod-f38eb4fe50427549db8957e5033b73f04b4d5c82/_build/src/github.com/projectatomic/libpod/cmd/podman/images.go:339 +0xce
main.imagesCmd(0xc420118420, 0x0, 0x0)
        /builddir/build/BUILD/libpod-f38eb4fe50427549db8957e5033b73f04b4d5c82/_build/src/github.com/projectatomic/libpod/cmd/podman/images.go:208 +0x5e5
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.HandleAction(0x1072920, 0x12a6570, 0xc420118420, 0x0, 0xc4202aa180)
        /builddir/build/BUILD/libpod-f38eb4fe50427549db8957e5033b73f04b4d5c82/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.Command.Run(0x121dd99, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1238597, 0x1c, 0x0, ...)
        /builddir/build/BUILD/libpod-f38eb4fe50427549db8957e5033b73f04b4d5c82/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/command.go:165 +0x47d
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.(*App).Run(0xc42017ea80, 0xc420030090, 0x3, 0x3, 0x0, 0x0)
        /builddir/build/BUILD/libpod-f38eb4fe50427549db8957e5033b73f04b4d5c82/_build/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/app.go:259 +0x6e8
main.main()
        /builddir/build/BUILD/libpod-f38eb4fe50427549db8957e5033b73f04b4d5c82/_build/src/github.com/projectatomic/libpod/cmd/podman/main.go:214 +0x1758
```

**Describe the results you expected:**
a list of images

**Additional information you deem important (e.g. issue happens only occasionally):**

After each buildah run, there is a skopeo copy to a registry. After some concurrent builds, skopeo copy started to fail with messages like this:
```
# skopeo copy --dest-tls-verify=false containers-storage:192.168.24.1:8787/tripleomaster/centos-binary-barbican-api:9ad93affedba8870315dd72c714770875ce24759_b72f0c42-u
pdated-20180904051626 docker://192.168.24.1:8787/tripleomaster/centos-binary-barbican-api:9ad93affedba8870315dd72c714770875ce24759_b72f0c42-updated-20180904051626

FATA[0017] Error writing blob: Patch http://192.168.24.1:8787/v2/tripleomaster/centos-binary-barbican-api/blobs/uploads/8ff1e93b-ce35-4d56-9764-e883ec9b7780?_state=S0RBuvNeY
SoWmrrtoXvpfhYkvg9gzAg_BLQziIbaQcV7Ik5hbWUiOiJ0cmlwbGVvbWFzdGVyL2NlbnRvcy1iaW5hcnktYmFyYmljYW4tYXBpIiwiVVVJRCI6IjhmZjFlOTNiLWNlMzUtNGQ1Ni05NzY0LWU4ODNlYzliNzc4MCIsIk9mZnNldC
I6MCwiU3RhcnRlZEF0IjoiMjAxOC0wOS0wNVQwMjozMDowOC4yOTkwMTczMjRaIn0%3D: open /var/lib/containers/storage/overlay/95b57c82098519d4d3ea5be43a300f419304aa49d8b9c9ddc05c78cd35c8aa
36/merged/etc/yum.conf: no such file or directory
```
**Output of `podman version`:**
podman version 0.8.2.1

**Output of `podman info`:**
host:
  Conmon:
    package: podman-0.8.2.1-1.gitf38eb4f.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 74bba30adae4fdcacf887d35e4d6331318765028-dirty'
  MemFree: 3969806336
  MemTotal: 8201625600
  OCIRuntime:
    package: runc-1.0.0-37.rc5.dev.gitad0f525.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 8579444736
  SwapTotal: 8589930496
  arch: amd64
  cpus: 4
  hostname: undercloud.localdomain
  kernel: 3.10.0-862.11.6.el7.x86_64
  os: linux
  uptime: 21h 47m 35.76s (Approximately 0.88 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.centos.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 18
  RunRoot: /var/run/containers/storage

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Centos 7 in an OpenStack cloud node, container packages from http://mirror.mtl01.inap.openstack.org:8080/cbs.centos/virt7-container-common-candidate/

**Comment by vrothberg** [comment]
Thanks for taking the time to open this issue, @steveb! I think this issue has been resolved in the meantime via https://github.com/containers/libpod/pull/1381 by @rhatdan. @rhatdan, can you confirm?

**Comment by steveb** [comment]
I'm seeing the exact same behaviour with podman-0.8.5-3.gitdc5a711.el7.x86_64.

The Dockerfile does a yum update on an existing image using a copied-in /etc/yum.repos.d and a small local repository of rpms - I can provide an example later.

I'll ask for a buildah release to see if that prevents storage getting into this state

**Comment by rhatdan** [comment]
@steveb Could you /var/lib/containers to /var/lib/containers.old

And then see if you can recreate this bug using the newer code.

**Comment by steveb** [comment]
I've just tried again starting with an empty /var/lib/containers, and git master of buildah, podman and skopeo.

I'm still seeing the same issue:

Running skopeo copy --dest-tls-verify=false containers-storage:192.168.24.1:8787/tripl
eomaster/centos-binary-barbican-api:9ad93affedba8870315dd72c714770875ce24759_b72f0c42-
updated-20180904051626 docker://192.168.24.1:8787/tripleomaster/centos-binary-barbican
-api:9ad93affedba8870315dd72c714770875ce24759_b72f0c42-updated-20180904051626
FATA[0000] Error writing blob: Patch http://192.168.24.1:8787/v2/tripleomaster/centos-
binary-barbican-api/blobs/uploads/e258738e-36e3-4e43-8993-2677aab42488?_state=D4kv390R
ARBthXyT8vyrgYfAGi-9f24_lNpSbPWOa157Ik5hbWUiOiJ0cmlwbGVvbWFzdGVyL2NlbnRvcy1iaW5hcnktYm
FyYmljYW4tYXBpIiwiVVVJRCI6ImUyNTg3MzhlLTM2ZTMtNGU0My04OTkzLTI2NzdhYWI0MjQ4OCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxOC0wOS0wNlQyMTo0NzoyNC4xNTQyNTAzMzdaIn0%3D: open /var/lib/
containers/storage/overlay/1d31b5806ba40b5f67bde96f18a181668348934a44c9253b420d5f04cfb4e37a/merged/anaconda-post.log: no such file or directory 


# podman images
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfc82f9]

goroutine 1 [running]:
main.getImagesTemplateOutput(0x13fbdc0, 0xc4200320f0, 0xc4200cec60, 0xc42042f780, 0xc, 0x10, 0x0, 0x0, 0x0, 0xc4202dd180, ...)
        /home/steveb/dev/go/src/github.com/containers/libpod/cmd/podman/images.go:297 +0x359
main.generateImagesOutput(0x13fbdc0, 0xc4200320f0, 0xc4200cec60, 0xc42042f780, 0xc, 0x10, 0x0, 0x0, 0x0, 0xc4202dd180, ...)
        /home/steveb/dev/go/src/github.com/containers/libpod/cmd/podman/images.go:341 +0xce
main.imagesCmd(0xc4201186e0, 0x0, 0x0)
        /home/steveb/dev/go/src/github.com/containers/libpod/cmd/podman/images.go:210 +0x5e5
github.com/containers/libpod/vendor/github.com/urfave/cli.HandleAction(0x10f9740, 0x1347ae8, 0xc4201186e0, 0x0, 0xc4202ac1e0)
        /home/steveb/dev/go/src/github.com/containers/libpod/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/containers/libpod/vendor/github.com/urfave/cli.Command.Run(0x12b3a2a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12cfb1c, 0x1c, 0x0, ...)
        /home/steveb/dev/go/src/github.com/containers/libpod/vendor/github.com/urfave/cli/command.go:165 +0x47d
github.com/containers/libpod/vendor/github.com/urfave/cli.(*App).Run(0xc42017ea80, 0xc42000c080, 0x2, 0x2, 0x0, 0x0)
        /home/steveb/dev/go/src/github.com/containers/libpod/vendor/github.com/urfave/cli/app.go:259 +0x6e8
main.main()
        /home/steveb/dev/go/src/github.com/containers/libpod/cmd/podman/main.go:240 +0x175b

**Comment by mheon** [comment]
We do an unconditional dereference on size at https://github.com/containers/libpod/blob/master/cmd/podman/images.go#L297

We should do a null check before that deref - will kill the segfault. Maybe we can print "Unknown" or similar for the size in that case?

**Comment by baude** [comment]
@steveb can you post a reproducer so we can fix this up?  Much appreciated.

**Comment by steveb** [comment]
I've got a fix working locally, proposing a pull request now.

**Comment by vrothberg** [comment]
Closing as the bug has been fixed via https://github.com/containers/libpod/pull/1423. Thanks, @steveb!
