### ISSUE TITLE
varlink: rmi of image with untagged layer: unexpected stdout

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2212]
In window 1:
```
# ./bin/podman varlink --timeout 0  unix:/run/podman/io.podman
```
In window 2:
```
podman run --name c1 alpine touch /test_a
podman commit c1 i1
podman run --name c2 i1 touch /test_a1
podman commit c2 i2

# Remove containers
podman rm --force c1 c2

# Remove first image
podman-remote rmi i1

# i1 is still around, it's just untagged
podman-remote images -a

# This command will cause output on the varlink window (SHA of i1)
podman-remote rmi i2
```

Podman built from master, 7838a13b61e, on f29.

**Comment by baude** [comment]
finally found the culprit is in image.go:360 ... putting this here for when I pick it up again.

**Comment by edsantiago** [comment]
Comparison of podman vs podman-remote behavior:
```
# podman run --name c1 alpine touch /test_a
# podman commit c1 i1
Getting image source signatures
Skipping blob 503e53e365f3 (already present): 5.52 MiB / 5.52 MiB [=========] 0s
Copying blob 587c5d809e91: 4.00 KiB / 4.00 KiB [============================] 0s
Copying config f9cd3c92c307: 773 B / 773 B [================================] 0s
Writing manifest to image destination
Storing signatures
f9cd3c92c3070c478b4aa398f56e11e42dddd0922ab743552e716e18efc9bf77
# podman run --name c2 i1 touch /test_a1
# podman commit c2 i2
Getting image source signatures
Skipping blob 503e53e365f3 (already present): 5.52 MiB / 5.52 MiB [=========] 0s
Skipping blob 587c5d809e91 (already present): 4.00 KiB / 4.00 KiB [=========] 0s
Copying blob 3d305faa3131: 1.50 KiB / 1.50 KiB [============================] 0s
Copying config 0d268077bd53: 893 B / 893 B [================================] 0s
Writing manifest to image destination
Storing signatures
0d268077bd53668045e16e34c1644abee1e45662a29346ad3878d7e98bb0d601
# podman rm --force c1 c2
5262006b8cb3c00044ac46027f83ae508b3a572ea294d31c207e5abb513ad7fd
821c57571d9a3dec6c13181b231b0974e81d57b490265241e2c64743c54ea70d
[ the above is the same in both cases. Below is the diff between podman & podman-remote]
----------------------------------------------------------------------------------------------------------------------
# podman rmi i1                        | # podman-remote rmi i1
Untagged: localhost/i1:latest          | [outputs the SHA of i1, even though that image isn't rm'ed]
# podman rmi i2                        | # podman-remote rmi i2
[sha of i1]                            | [sha of i2 -- SHA of i1 is output in the varlink window]
[sha of i2]

**Comment by rhatdan** [comment]
@edsantiago @baude @jwhonce Is this fixed now?

**Comment by baude** [comment]
no, this is not a simple fix. i looked at it this morning and it is going to required more work that i have today.

**Comment by rhatdan** [comment]
@edsantiago @baude Any update on this?  Fixed still in progress? Forgotten?

**Comment by edsantiago** [comment]
Still present in d10f68ac95e13535f90d9b643ac2d7530178c21d.

FWIW the 'varlink' process is quite noisy; from a short test run, I get tons of output like:
```
# podman varlink --timeout=0 unix:/run/podman/io.podman
rm false
ERRO[0234] unable to find flag trace
ERRO[0234] unable to find flag syslog
rm false
ERRO[0235] unable to find flag trace
ERRO[0235] unable to find flag syslog
detach false
rm false
```
And, oh dear, `podman-remote pull alpine` is SEGVing.

**Comment by baude** [comment]
I have a PR to fix this original report but i need to coordinate with the cockpit folks and we're not quiet there yet.

**Comment by baude** [comment]
this is now fixed ... @edsantiago can you confirm and close?

**Comment by edsantiago** [comment]
master is completely broken right now:
```
podman run --name c1 alpine touch /test_a
option parsing failed: Unknown option -n
Error: write child: broken pipe
```
Will check once that's fixed. (Will also file issue if one isn't already filed)

**Comment by edsantiago** [comment]
tested on master @ c93b8d6b02c7ec0c91af34481133001421b9628d; looks to be fixed. Thank you!
