### ISSUE TITLE
podman pod top on pod test on Ubuntu

### ISSUE THREAD

**Issue by cevich** [containers/libpod#2548]
/kind bug

**Description**

Since about Feb. 25th this test has been failing on occasion, but only on Ubuntu

**Steps to reproduce the issue:**

1. Execute Cirrus-CI tests on ubuntu

**Describe the results you received:**

Sometimes it fails.

**Describe the results you expected:**

It should always pass

**Additional information you deem important (e.g. issue happens only occasionally):**

Several people have looked at the test-code and output, but the failure mode is not obvious.  Attempts to fix command-execution races did not seem to affect the frequency of this test failing. :disappointed:

**Comment by cevich** [comment]
@baude @mheon @rhatdan All ideas are welcome.  Seems more likely to be a test-bug than a podman bug, but I don't think we have enough data to say.  Has anyone been able to reproduce this outside of CI?

**Comment by rhatdan** [comment]
Is it always the same line?

**Comment by cevich** [comment]
Good thought, I think so, but it's worth checking.  All/Most of the red graph lines here are the Ubuntu problem: https://cirrus-ci.com/github/containers/libpod/master

(I'm checking to see if  the output is the same)

**Comment by cevich** [comment]
Interesting...this is ***NOT*** only Ubuntu failing.  Here are the handful of post-merge tests I pseudo randomly clicked on to look at:

* https://cirrus-ci.com/task/6565773473480704
* https://cirrus-ci.com/task/5431353895026688
* https://cirrus-ci.com/task/5470504010907648
* https://cirrus-ci.com/task/4686723012362240
* https://cirrus-ci.com/task/5974720085229568
* https://cirrus-ci.com/task/6288311275487232
* https://cirrus-ci.com/task/4814335374262272
* https://cirrus-ci.com/task/4835431347650560

*Hint: There's a download button that allows grepping the entire log.*

**Comment by cevich** [comment]
Editing and adding notes above as I look through logs.

**Comment by cevich** [comment]
@rhatdan I would conclude yes, same line, fails on F28, F29 but more likely Ubuntu.  It's always one test on ubuntu, but three on Fedora (maybe insignificant fact).  These seem to be the best examles:

* https://cirrus-ci.com/task/5431353895026688  (ubuntu `test/e2e/pod_top_test.go:133`)
* https://cirrus-ci.com/task/5470504010907648  (F28 `test/e2e/pod_top_test.go:133`)
* https://cirrus-ci.com/task/6288311275487232  (F29 `test/e2e/pod_top_test.go:133`)
* https://cirrus-ci.com/task/4814335374262272  (another ubuntu example)
* https://cirrus-ci.com/task/4835431347650560  (another F29 example)

**Comment by cevich** [comment]
(Note, "examles" are simply a more superior version of examples)

**Comment by cevich** [comment]
Hypothesis: We only see this in CI, never in the "wild"

Theory: Could this be a devel-vs-ci "gap" issue - where we build podman dependencies from source that are out-of-sync with actual, real-world packaged dependencies that developers and users use.

Ideas of things to check:

1. Is this is reproducible manually, using a VM image from CI.
2. Is this reproducible manually, on a development workstation w/o any special CI-stuffs
3. Can it be reproduced quicker by only running the podman top tests in a loop
4. Does it happen more or less frequently when changing X (where X could be memory, cpu, disk, or network activity).

**Comment by cevich** [comment]
@edsantiago It's expecting to see "three lines of output" (like in your example).  Somehow it's only getting two lines.  Sometimes :S  

Ginkgo is actually somewhat of a sub-framework, nested inside Go's built-in testing system. There should be a "T" variable somewhere (https://godoc.org/github.com/onsi/ginkgo#GinkgoTestingT) that shadows `testing.T` which is a pointer to a structure that provides the logging/output calls you're looking for:  https://golang.org/pkg/testing/#T

**Comment by edsantiago** [comment]
What makes you think it's "only getting two lines"? The only thing I can tell from the test source code is "it's getting non-three". As in, I've got a BATS test now running this, and sometimes it gets three lines, sometimes four (as in the above). The `/pause` seems to be arbitrary.

**Comment by mheon** [comment]
Wait, what? Some invocations are missing a pause container?

**Comment by edsantiago** [comment]
Glad I have scrollback:
```
$ podman pod top e14226b14d05a8ac3e11d8ae3cd795284bcc5de49f96074b1a99609af434282d
   USER   PID   PPID   %CPU    ELAPSED        TTY   TIME   COMMAND
   root   1     0      0.000   1.136282978s   ?     0s     top -d 2 
   root   1     0      0.000   1.143966075s   ?     0s     top -d 2 
```
Oh and look, I also see one with `/pause` but only one `top`:
```
$ podman pod top a791a0c2588a3b52162bac77d53d3dc0576073b018edc86c398eeff3681fce96
   USER   PID   PPID   %CPU    ELAPSED        TTY   TIME   COMMAND
   root   1     0      0.000   1.251342108s   ?     0s     top -d 2 
   0      1     0      0.000   1.257110272s   ?     0s     /pause 
```
(ignore the `$` prompt; that's an artifact of my script. Actual runs are as root).

**Comment by cevich** [comment]
> Wait, what? Some invocations are missing a pause container?

YES!  This is what I see in the logs...

**Comment by cevich** [comment]
...

```
output: 1e48d58e21c61051d4e6f9f462f475e21a4f06e21bd357f965997fe5d5b71331
Running: /var/tmp/go/src/github.com/containers/libpod/bin/podman --root /tmp/podman_test221051158/crio --runroot /tmp/podman_test221051158/crio-run --runtime /usr/bin/runc --conmon /usr/libexec/podman/conmon --cni-config-dir /etc/cni/net.d --cgroup-manager cgroupfs --storage-driver vfs pod top 4dd5435763005fc832cb81512c033044b850a97ea4190b4d7ec4a17cbf3b4810
USER   PID   PPID   %CPU    ELAPSED        TTY   TIME   COMMAND
root   1     0      0.000   1.520002212s   ?     0s     top -d 2 
output: USER PID PPID %CPU ELAPSED TTY TIME COMMAND root 1 0 0.000 1.520002212s ? 0s top -d 2
```

**Comment by mheon** [comment]
Alright that is bloody fascinating.
@haircommander We create the pause container before returning the pod, right? This does not sound possible

**Comment by cevich** [comment]
@edsantiago I'm realizing also that we don't include much helpful output when the test PASSES.  Getting more details out of the tests is almost always a helpful thing.

**Comment by haircommander** [comment]
Yup! are we sure the infra container is being made (I mention it because e2e tests don't create a pause container in a call to ```podmanTest.CreatePod("")  ```)

**Comment by cevich** [comment]
Oh!  So if the pause container is created/destroyed asynchronously to examining top-output, that all but guarantees the test will race depending on system-load / conditions.

For these tests using 'top', can we make them use the events/logs to wait for the pause-container to appear, then disappear, before running top?

Also, I think this test should be checking against a regex, not just counting lines.  It's conceivable than an error-message could satisfy the 3-line condition, while masking an actual problem we want to know about immediately.

**Comment by mheon** [comment]
The creation shouldn't be async here, though.

Either we have a pause container, made when we made the pod, or we don't. We are in some sort of uncertain state where it exists only half the time.

**Comment by edsantiago** [comment]
To be precise: I don't know if there is a `/pause` container or not. I do know that, under some indeterminate circumstances, `podman pod top` is not showing one. I don't know if it's a does-not-exist problem or a not-being-shown problem.

**Comment by cevich** [comment]
@edsantiago I think it's both in a way.  It exists, then goes away before or during execution of top.

Perhaps it's silly, but couldn't a simple fix be to just play-dumb about it: filter out any possibly existing lines containing 'pause'. Since it would be good (IMH) to compare the output to a regex instead of a line-count anyway :smile:

**Comment by edsantiago** [comment]
That depends on whether it's important to test for a pause container or not. Here's my short BATS test for reference:
```bash
@test "podman pod top - on pod with containers in different namespaces" {
    skip_if_rootless

    run_podman pod create
    podid="$output"

    # FIXME: how do we wait for ready?
    run_podman run -d --pod $podid $PODMAN_TEST_IMAGE_FQN top -d 2
    run_podman run -d --pod $podid $PODMAN_TEST_IMAGE_FQN top -d 2

    run_podman pod top $podid
    # There should be two 'top -d 2' processes running
    is "$output" ".*root.*top -d 2.*root.*top -d 2" "two 'top' containers"

    # There should be a /pause container
    is "$output" ".*0 \+1 \+0 \+[0-9. ?s]\+/pause" "there is a /pause container"

    run_podman pod rm -f $podid
}
```

**Comment by mheon** [comment]
We expect that `pod create` will create a pause container unless explicitly instructed not to, and that pause container will appear in `podman pod top` for that pod if a container shares any namespaces with it.

**Comment by cevich** [comment]
@edsantiago I don't think it's important.  My understanding (someone correct me) is that the pause container is a necessary but temporary artifact to reserve resources.  So we need it when we need it, otherwise we ignore it.  That's why I think it might simply be safe for the test to ignore it.  If the pause container mechanism ever breaks, LOTS of other tests will fail.

**Comment by mheon** [comment]
Also - what does "in different namespaces" mean in this test? @haircommander Did you write this one originally?

**Comment by cevich** [comment]
oh okay, so for this failing test specifically, we _DO_ expect to see it in the top output?

**Comment by mheon** [comment]
Yes.

I also fail to see anything that would cause different namespaces in this test.

**Comment by mheon** [comment]
At least, the Bash version from @edsantiago

**Comment by edsantiago** [comment]
Sorry - I just copied the test name from e2e. /ihavenoideawhatimdoing

Okay, so enough: we know we have a problem. We have a likely smoking gun for test failures. I will back away slowly and let the professionals do their jobs.

**Comment by mheon** [comment]
I also don't see separate namespaces in the Go test.
Does this test predate infra containers?
Should we just force `--infra=false` for this test?

**Comment by haircommander** [comment]
@mheon I think @baude wrote this. He wrote pod top at least

**Comment by cevich** [comment]
@mheon Remember this _mostly_ passes on all platforms numbers-wise.  So there must be a race.

@edsantiago no not at all, please stay.  This problem was created by "experts", so having eyes unfamiliar with the code is actually very useful.

**Comment by mheon** [comment]
I think that whatever the original intent of this test was, it's no longer testing for it.

However, it is showing some properly strange behaviour, so it's clearly not a bad test - it caught... whatever is happening here?

**Comment by haircommander** [comment]
It has come to my attention that I did in fact write this. Sorry @baude I hope you can forgive me. That said, I definitely don't remember why I wrote the test haha

**Comment by rhatdan** [comment]
Since the only difference between this test and the previous is the sharing of the pid namespace, I guess the title should add pid namespae.

	It("podman pod top on pod with containers in different pid namespaces", func() {

**Comment by edsantiago** [comment]
Just to add to the general confusion: I _thought_ I had a fixed test for this:
```bash
    # Start two containers...
    run_podman run -d --pod $podid $IMAGE top -d 2
    cid1="$output"
    run_podman run -d --pod $podid $IMAGE top -d 2
    cid2="$output"

    # ...and wait for them to actually start.
    wait_for_output "PID \+PPID \+USER " $cid1
    wait_for_output "PID \+PPID \+USER " $cid2

    # Both containers have emitted at least one top-like line.
    # Now run 'pod top', and expect two 'top -d 2' processes running.
    run_podman pod top $podid
    is "$output" ".*root.*top -d 2.*root.*top -d 2" "two 'top' containers"
```
(the key being: run `podman logs` on each container, wait until we see PID-PPID-USER, and assume that means each container has actually started).

Even with that, I just got this:
```
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #|     FAIL: two 'top' containers
   #| expected: '.*root.*top -d 2.*root.*top -d 2'
   #|   actual: 'USER   PID   PPID   %CPU    ELAPSED        TTY   TIME   COMMAND'
   #|         > 'root   1     0      0.000   1.743555723s   ?     0s     top -d 2 '
   #|         > '0      1     0      0.000   1.747961884s   ?     0s     /pause '
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I realize there is much I don't understand about pods, but this seems weird enough to merit a cry for help. (If not for my little test, at least for the sake of the e2e one).

**Comment by baude** [comment]
this should be corrected with #2560 when it merges

**Comment by cevich** [comment]
@edsantiago don't worry, we're all uniquely confused in our own special ways :smile:   Seriously though, I think this issue exists because no one person understood/understands all the implications of the way the test was written.

We'll see if Brent's PR either fixes this, or makes it monumentally more difficult to reproduce :grinning:

**Comment by mheon** [comment]
@edsantiago I think your `pod create` is missing the flag to disable infra container creation, which the original Go test has.

**Comment by edsantiago** [comment]
@mheon yes, but the point of my previous comment was that, even if I start two `top` containers, and have the test script wait for output from each one (thus theoretically eliminating race conditions) I still see a situation in which `podman pod top` shows only one `top` container. Is there something big I'm not understanding (e.g. "oh, podman pod top doesn't actually show all processes") ?

**Comment by mheon** [comment]
Huh. That does sound like a bug.

**Comment by edsantiago** [comment]
For grins, I modified my test script to run `podman pod create --infra=false`, then started a loop to see if it would fail. Didn't take too long:
```
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #|     FAIL: two 'top' containers
   #| expected: '.*root.*top -d 2.*root.*top -d 2'
   #|   actual: 'USER   PID   PPID   %CPU    ELAPSED        TTY   TIME   COMMAND'
   #|         > 'root   1     0      0.000   2.091225978s   ?     0s     top -d 2 '
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
(I didn't define a timer or counter, or even watch the loop, but it was less than ten minutes. Subsequent loop failed on the second, the next after about 8.) `podman-1.1.2-1.git0ad9b6b.fc29`. LMK if you want access to the system.

**Comment by cevich** [comment]
perhaps the problem all along here is within top itself.  As in, it's racing against the kernel under some conditions.  WDYT if the test started a background process, e.g. `sleep 1d`, then specifically tested for it's presence ignoring other lines.  In other words, if `sleep 1d` appears in `ps` output the test passes.  This is guaranteed not to race because the background process has returned control to the shell before the `ps` is executed.

**Comment by rhatdan** [comment]
My original PR to fix this replaced top with sleep, I think sleep is a much better way to test this.

**Comment by cevich** [comment]
Yeah,  I think we weren't yet clear on the purpose of this test.  It seems the point is to confirm one process is visible to another, in the same context.  So after running sleep, the test should also try to find it (in proc or ps output).  I don't remember if your PR included that or not.

**Comment by mheon** [comment]
`top` vs `sleep` shouldn't matter here. We're not finding the container in question through CGroups, which doesn't depend on what's running in it.

**Comment by cevich** [comment]
@mheon I don't understand "not finding the container...though".  Does that mean the test is failing a requirement, or the test doesn't care?

If top vs sleep doesn't matter, then couldn't we make it even simpler by using `/bin/true` ?

**Comment by mheon** [comment]
@cevich Well, we do need the container to remain running long enough for `top` to see it, so `true` probably isn't a good choice - it returns immediately.

This seems to be some sort of race. We make two containers in a pod with `podman run` which should not return until the containers have successfully started, then run `podman pod top` to check how many containers in the pod are running, and find only one container. We're reading the processes that are running via CGroups, so potentially they're slow to update running processes, or maybe the second container is just starting slow enough that we don't show it as running yet.

The easy solution, from @baude in his PR to fix the test, was to just add some sleeps between the run commands and pod stop, to give the system state time to settle.

**Comment by cevich** [comment]
@mheon thanks for the explanation, that helps a lot.  My skull-calculator has been a bit smarmy fighting some bug, so I've not been watching closely.  Did @baude PR improve the situation with this test?

**Comment by baude** [comment]
yes

**Comment by cevich** [comment]
Excellent, lemmie close this then :smile:
