### ISSUE TITLE
podman pull  nginx@sha256:57a226fb6ab6823027c0704a9346a890ffb0cacde06bc19bbc234c8720673555 fails

### ISSUE THREAD

**Issue by kkimdev** [containers/libpod#3255]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman pull nginx` succeeds but the following podman pull fails.

**Steps to reproduce the issue:**

1. `podman pull  nginx@sha256:57a226fb6ab6823027c0704a9346a890ffb0cacde06bc19bbc234c8720673555`

**Describe the results you received:**
```
$ podman pull  nginx@sha256:57a226fb6ab6823027c0704a9346a890ffb0cacde06bc19bbc234c8720673555
Trying to pull docker.io/library/nginx@sha256:57a226fb6ab6823027c0704a9346a890ffb0cacde06bc19bbc234c8720673555...ERRO[0001] Error pulling image ref //nginx@sha256:57a226fb6ab6823027c0704a9346a890ffb0cacde06bc19bbc234c8720673555: Digest of source image's manifest would not match destination reference
Failed
Error: error pulling image "nginx@sha256:57a226fb6ab6823027c0704a9346a890ffb0cacde06bc19bbc234c8720673555": unable to pull nginx@sha256:57a226fb6ab6823027c0704a9346a890ffb0cacde06bc19bbc234c8720673555: 1 error occurred:
        * Digest of source image's manifest would not match destination reference
```

**Describe the results you expected:**
The following is the output using docker
```
$ docker pull  nginx@sha256:57a226fb6ab6823027c0704a9346a890ffb0cacde06bc19bbc234c8720673555
sha256:57a226fb6ab6823027c0704a9346a890ffb0cacde06bc19bbc234c8720673555: Pulling from library/nginx
e7c96db7181b: Pull complete
264026bbe255: Pull complete
a71634c55d29: Pull complete
5595887beb81: Pull complete
Digest: sha256:57a226fb6ab6823027c0704a9346a890ffb0cacde06bc19bbc234c8720673555
Status: Downloaded newer image for nginx@sha256:57a226fb6ab6823027c0704a9346a890ffb0cacde06bc19bbc234c8720673555
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.3.2-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.3.2-dev
host:
  BuildahVersion: 1.9.0-dev
  Conmon:
    package: 'conmon: /usr/libexec/crio/conmon'
    path: /usr/libexec/crio/conmon
    version: 'conmon version 0.2.0, commit: '
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 5777891328
  MemTotal: 17057861632
  OCIRuntime:
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 51205361664
  SwapTotal: 51539607552
  arch: amd64
  cpus: 8
  hostname: DESKTOP-BG5LGLR
  kernel: 4.4.0-17134-Microsoft
  os: linux
  rootless: false
  uptime: 98h 34m 23.48s (Approximately 4.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: <unknown>
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 10 WSL Ubuntu

**Comment by mheon** [comment]
@mtrmac PTAL - seems like this is coming out of c/image?

WSL may be involved here, but not certain how. @kkimdev are you on the new version of WSL, that uses a VM as opposed to emulating syscalls? I don't know if we can expect proper behavior on the older versions of WSL.

**Comment by kkimdev** [comment]
@mheon btw, do you mind quickly testing the above pull command?  I'm not sure if it's WSL specific or not, since I can do `podman pull nginx` just fine.

**Comment by mheon** [comment]
`* Digest of source image's manifest would not match destination reference`

Same error, 1.2.0 in Fedora packaged Podman

**Comment by kkimdev** [comment]
upstream issue: https://github.com/cri-o/cri-o/issues/2157

**Comment by mtrmac** [comment]
Yeah, https://github.com/cri-o/cri-o/issues/2157#issuecomment-475423356 . I don’t quite know how to deal with this well. I suppose doing what Docker does, and recording the digests but not verifying them at any point, is the best we can realistically do, but by now it’s likely enough to break someone.

**Comment by rhatdan** [comment]
@mtrmac @kkimdev Do we still have this issue?

**Comment by TomSweeneyRedHat** [comment]
I've added the do-not-close label.  Looks to be around still in 1.6.2 anyway.

**Comment by nalind** [comment]
Yeah, this would have been fixed by #4310, but that was after 1.6.2.

**Comment by rhatdan** [comment]
Since this is fixed in 1.6.3 closing.

**Comment by johnfosborneiii** [comment]
I'm on Fedora 31 and podman 1.6.2 is still the latest and I'm hitting this issue.

**Comment by mheon** [comment]
v1.7.0 has been released and should be in updates/testing either now, or very soon.

**Comment by johnfosborneiii** [comment]
I still see 1.6.2. This is pretty urgent. Trying to resolve a hot issue for a customer. Do I need to build from source to get 1.6.3 on Fedora 31?

sudo dnf --enablerepo=updates-testing list podman*
Last metadata expiration check: 0:01:31 ago on Wed 08 Jan 2020 03:21:41 PM EST.
Installed Packages
podman.x86_64                                                                                                 2:1.6.2-2.fc31                                                                                                   @fedora        
podman-manpages.noarch                                                                                        2:1.6.2-2.fc31                                                                                                   @fedora        
Available Packages
podman-compose.noarch                                                                                         0.1.5-2.git20191107.fc31                                                                                         updates        
podman-docker.noarch                                                                                          2:1.6.2-2.fc31                                                                                                   updates-testing
podman-docker.noarch                                                                                          2:1.6.2-2.fc31                                                                                                   fedora         
podman-remote.x86_64                                                                                          2:1.6.2-2.fc31                                                                                                   updates-testing
podman-remote.x86_64                                                                                          2:1.6.2-2.fc31                                                                                                   fedora         
podman-tests.x86_64                                                                                           2:1.6.2-2.fc31                                                                                                   updates-testing
podman-tests.x86_64                                                                                           2:1.6.2-2.fc31                                                                                                   fedora

**Comment by mheon** [comment]
https://koji.fedoraproject.org/koji/buildinfo?buildID=1427538

RPMs for 1.7 can be found here
