### ISSUE TITLE
podman is no longer installable alongside containerd.io on ubuntu

### ISSUE THREAD

**Issue by flx42** [containers/libpod#3453]
With the update of the `containerd.io` package to 1.2.6-3 (probably today with the release of docker ce 18.09.7), runc moved from `/usr/sbin/runc` to `/usr/bin/runc`, which directly clashes with the `cri-o-runc` package:

```
$ sudo apt-get install -y podman
[...]

Preparing to unpack .../cri-o-runc_1.0.0-rc6-1~dev~ubuntu18.04~ppa44_amd64.deb ...
Unpacking cri-o-runc (1.0.0-rc6-1~dev~ubuntu18.04~ppa44) ...
dpkg: error processing archive /var/cache/apt/archives/cri-o-runc_1.0.0-rc6-1~dev~ubuntu18.04~ppa44_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/runc', which is also in package containerd.io 1.2.6-3
Selecting previously unselected package podman.
Preparing to unpack .../podman_1.4.0-1~ubuntu18.04~ppa1_amd64.deb ...
Unpacking podman (1.4.0-1~ubuntu18.04~ppa1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/cri-o-runc_1.0.0-rc6-1~dev~ubuntu18.04~ppa44_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by vrothberg** [comment]
Thanks for opening the issue, @flx42. @lsm5 PTAL

**Comment by rhatdan** [comment]
The Docker/containerd package is providing its own version of runc, as well as Podman.  Not sure if Podman can work with containerd version.  We are having this same issue with Fedora, although in the Fedora case, we have a separate runc package which each tool should just use, rather then attempting to provide their own.

**Comment by vsoch** [comment]
I just ran into this issue too - in my case I had installed podman a few months back, and was re-installing docker today with instructions from [here](https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce). When I hit the apparmour error I thought it was a repeat of this one https://github.com/docker/for-linux/issues/503 but my original fixes didn't work this time. I purged everything (docker* and runc) (but not podman) and went through the steps in the previous link, and hit this error down to the T.  I had to purge crio-run-c to get Docker installed (and working) again:

```bash
sudo apt-get purge docker*
sudo apt-get remove cri-o-runc
sudo apt-get remove runc
sudo apt update
sudo apt-get install docker-ce docker-ce-cli containerd.io
which docker
docker run hello-world
```
And in those brief moments when I couldn't do anything with containers I saw my life flash before my eyes... just kidding :)  For completeness, I'm on ubuntu 18.04.

**Comment by sic-bre** [comment]
Any status or recommendations the the best way to work around in the short term?  I kind of need to have docker and podman side by side (on Ubuntu 18.04 LTS) for doing an evaluation.

**Comment by lsm5** [comment]
@mheon so, our runc can be neither in `/usr/bin` nor `/usr/sbin`. What other paths can podman use? `/usr/libexec/podman/runc` maybe, same as conmon?

**Comment by mheon** [comment]
Our default runc paths are:

```
	    "/usr/bin/runc",
	    "/usr/sbin/runc",
	    "/usr/local/bin/runc",
	    "/usr/local/sbin/runc",
	    "/sbin/runc",
	    "/bin/runc",
	    "/usr/lib/cri-o-runc/sbin/runc"
```

We can definitely get a /usr/libexec path in there if that's how we want to go, just need to get a patch in to add it as a valid path before we swap destinations.

**Comment by lsm5** [comment]
ah ya, sorry about the brainfart, I remember our runc had a symlink /usr/bin/runc to /usr/lib/cri-o-runc/sbin/runc. I don't quite remember the issue which requested for that symlink. I'll get rid of the symlink.

**Comment by lsm5** [comment]
@flx42 @vsoch @sic-bre I just pushed runc 1.0.0-rc8 to ppa. It only has runc in `/usr/lib/cri-o-runc/sbin`. Please reopen if it doesn't work. HTH

**Comment by sic-bre** [comment]
Thank you that seems to have worked!  I have the latest docker-ce 19.03.0 and podman 1.4.3 running side by side on a fully patched Ubuntu 18.04 LTS.  They both run the docker.io/library/hello-world after the default repositories are configured.

**Comment by rhatdan** [comment]
Excellent.

**Comment by fullstackwebdev** [comment]
Sorry, how do I use PPA 1.0.0-rc8?

How do I simply point from "rc6" to "rc8"

Following the instructions I still get an error
```
Do you want to continue? [Y/n] 
Setting up dpkg (1.18.4ubuntu1.6) ...
Processing triggers for man-db (2.7.5-1) ...
(Reading database ... 263412 files and directories currently installed.)
Preparing to unpack .../cri-o-runc_1.0.0-rc6-1~ubuntu16.04.2~ppa83_amd64.deb ...
Unpacking cri-o-runc (1.0.0-rc6-1~ubuntu16.04.2~ppa83) ...
dpkg: error processing archive /var/cache/apt/archives/cri-o-runc_1.0.0-rc6-1~ubuntu16.04.2~ppa83_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/runc', which is also in package containerd.io 1.2.6-3
Errors were encountered while processing:
 /var/cache/apt/archives/cri-o-runc_1.0.0-rc6-1~ubuntu16.04.2~ppa83_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)


```

**Comment by lsm5** [comment]
> Sorry, how do I use PPA 1.0.0-rc8?
> 
> How do I simply point from "rc6" to "rc8"
> 
> Following the instructions I still get an error
> 
> ```
> Do you want to continue? [Y/n] 
> Setting up dpkg (1.18.4ubuntu1.6) ...
> Processing triggers for man-db (2.7.5-1) ...
> (Reading database ... 263412 files and directories currently installed.)
> Preparing to unpack .../cri-o-runc_1.0.0-rc6-1~ubuntu16.04.2~ppa83_amd64.deb ...
> Unpacking cri-o-runc (1.0.0-rc6-1~ubuntu16.04.2~ppa83) ...
> dpkg: error processing archive /var/cache/apt/archives/cri-o-runc_1.0.0-rc6-1~ubuntu16.04.2~ppa83_amd64.deb (--unpack):
>  trying to overwrite '/usr/bin/runc', which is also in package containerd.io 1.2.6-3
> Errors were encountered while processing:
>  /var/cache/apt/archives/cri-o-runc_1.0.0-rc6-1~ubuntu16.04.2~ppa83_amd64.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```

Seems like I haven't gotten rid of that symlink in 16.04 runc. I'll update in a bit.

**Comment by lsm5** [comment]
Should be fixed now. cri-o-runc only installs to `/usr/lib/cri-o-runc/sbin/runc`. Please reopen if the issue still persists.
