### ISSUE TITLE
running podman as sudo cause umask of 0000 inside of container. why?

### ISSUE THREAD

**Issue by wdouglascampbell** [containers/libpod#5506]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

In trying to figure out some permissions issues involved with attempting to share a local folder between two containers: one running rootful and one running rootless, I discovered some strange behavior with umask.

Running podman rootless, the default umask is always 0022.
Running sudo podman, the default umask is always 0000.
Running sudo docker, the default umask is always 0022.

I would expect the same result in all cases but it isn't that way.

**Steps to reproduce the issue:**

1.

`podman run --rm -it alpine:latest /bin/sh
/ # umask
0022`

2.

`sudo podman run --rm -it alpine:latest /bin/sh
/ # umask
0000`

3.

`sudo docker run --rm -it alpine:latest /bin/sh
/ # umask
0022`

**Describe the results you received:**

seeing default umask of 0000 when running sudo podman

**Describe the results you expected:**

expected to get default umask of 0022

**Output of `podman version`:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
[core@localhost mnt]$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.6
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 2521047040
  MemTotal: 4121198592
  OCIRuntime:
    name: runc
    package: runc-1.0.0-102.dev.gitdc9208a.fc31.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: 96f6022b37cbe12b26c9ad33a24677bec72a9cc3
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 1
  eventlogger: journald
  hostname: localhost.localdomain
  kernel: 5.5.5-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 22h 0m 20.5s (Approximately 0.92 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /var/home/core/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /var/home/core/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /run/user/1000/containers
  VolumePath: /var/home/core/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.8.0-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora CoreOS

**Comment by giuseppe** [comment]
I am not able to reproduce, I am using the same version of runc and podman as reported above.

Is your reproducer just `podman --runtime /usr/bin/runc run --rm -ti alpine sh -c 'umask`?

Are you sure you are not using crun as the runtime when running as root?  There was an issue with an older crun version but that should be fixed now

**Comment by wdouglascampbell** [comment]
Okay.  If I use that --runtime parameter I get the expected results but for some reason if I just use:

`
sudo podman run --rm -ti alpine sh -c 'umask'
`
with no `--runtime=/usr/bin/runc`, I still get `0000`.

I'm not really familiar though with that parameter.  What else would my Fedora CoreOS system be using instead of runc and how might I find out?

Thanks!

**Comment by mheon** [comment]
Can you make a container without `--runtime` and provide the output of `podman inspect` for that container? It should contain the name of the OCI runtime in use.

**Comment by rhatdan** [comment]
Also `podman info` which should show the version.

**Comment by wdouglascampbell** [comment]
Sure.  I created a container using `sudo podman --rm -ti alpine /bin/sh` and then switched to another session and inspect it and got the following (sorry the formatting is so bunched up):

`
[
    {
        "Id": "74340be6f373e5febf23b28e2fb88983dc0e42dd203b1d0c3af8dba01d2e2d61",
        "Created": "2020-03-17T01:30:48.786055569+08:00",
        "Path": "/bin/sh",
        "Args": [
            "/bin/sh"
        ],
        "State": {
            "OciVersion": "1.0.1-dev",
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 3311,
            "ConmonPid": 3307,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-03-17T01:30:49.300816462+08:00",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Healthcheck": {
                "Status": "",
                "FailingStreak": 0,
                "Log": null
            }
        },
        "Image": "e7d92cdc71feacf90708cb59182d0df1b911f8ae022d29e8e95d75ca6a99776a",
        "ImageName": "docker.io/library/alpine:latest",
        "Rootfs": "",
        "Pod": "",
        "ResolvConfPath": "/var/run/containers/storage/overlay-containers/74340be6f373e5febf23b28e2fb88983dc0e42dd203b1d0c3af8dba01d2e2d61/userdata/resolv.conf",
        "HostnamePath": "/var/run/containers/storage/overlay-containers/74340be6f373e5febf23b28e2fb88983dc0e42dd203b1d0c3af8dba01d2e2d61/userdata/hostname",
        "HostsPath": "/var/run/containers/storage/overlay-containers/74340be6f373e5febf23b28e2fb88983dc0e42dd203b1d0c3af8dba01d2e2d61/userdata/hosts",
        "StaticDir": "/var/lib/containers/storage/overlay-containers/74340be6f373e5febf23b28e2fb88983dc0e42dd203b1d0c3af8dba01d2e2d61/userdata",
        "OCIConfigPath": "/var/lib/containers/storage/overlay-containers/74340be6f373e5febf23b28e2fb88983dc0e42dd203b1d0c3af8dba01d2e2d61/userdata/config.json",
        "OCIRuntime": "crun",
        "LogPath": "/var/lib/containers/storage/overlay-containers/74340be6f373e5febf23b28e2fb88983dc0e42dd203b1d0c3af8dba01d2e2d61/userdata/ctr.log",
        "LogTag": "",
        "ConmonPidFile": "/var/run/containers/storage/overlay-containers/74340be6f373e5febf23b28e2fb88983dc0e42dd203b1d0c3af8dba01d2e2d61/userdata/conmon.pid",
        "Name": "busy_kalam",
        "RestartCount": 0,
        "Driver": "overlay",
        "MountLabel": "system_u:object_r:container_file_t:s0:c633,c704",
        "ProcessLabel": "system_u:system_r:container_t:s0:c633,c704",
        "AppArmorProfile": "",
        "EffectiveCaps": [
            "CAP_CHOWN",
            "CAP_DAC_OVERRIDE",
            "CAP_FSETID",
            "CAP_FOWNER",
            "CAP_MKNOD",
            "CAP_NET_RAW",
            "CAP_SETGID",
            "CAP_SETUID",
            "CAP_SETFCAP",
            "CAP_SETPCAP",
            "CAP_NET_BIND_SERVICE",
            "CAP_SYS_CHROOT",
            "CAP_KILL",
            "CAP_AUDIT_WRITE"
        ],
        "BoundingCaps": [
            "CAP_CHOWN",
            "CAP_DAC_OVERRIDE",
            "CAP_FSETID",
            "CAP_FOWNER",
            "CAP_MKNOD",
            "CAP_NET_RAW",
            "CAP_SETGID",
            "CAP_SETUID",
            "CAP_SETFCAP",
            "CAP_SETPCAP",
            "CAP_NET_BIND_SERVICE",
            "CAP_SYS_CHROOT",
            "CAP_KILL",
            "CAP_AUDIT_WRITE"
        ],
        "ExecIDs": [],
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/var/lib/containers/storage/overlay/5216338b40a7b96416b8b9858974bbe4acc3096ee60acbc4dfb1ee02aecceb10/diff",
                "MergedDir": "/var/lib/containers/storage/overlay/d4803b384b193b91034673be26c6998583bc9941b37c4daece641d3f6364f2f8/merged",
                "UpperDir": "/var/lib/containers/storage/overlay/d4803b384b193b91034673be26c6998583bc9941b37c4daece641d3f6364f2f8/diff",
                "WorkDir": "/var/lib/containers/storage/overlay/d4803b384b193b91034673be26c6998583bc9941b37c4daece641d3f6364f2f8/work"
            }
        },
        "Mounts": [],
        "Dependencies": [],
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": [],
            "SandboxKey": "/var/run/netns/cni-a7335410-6bcd-57b1-b6a1-0ab27a41a22f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "10.88.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "10.88.0.47",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "fe:59:44:d0:3f:73"
        },
        "ExitCommand": [
            "/usr/bin/podman",
            "--root",
            "/var/lib/containers/storage",
            "--runroot",
            "/var/run/containers/storage",
            "--log-level",
            "error",
            "--cgroup-manager",
            "systemd",
            "--tmpdir",
            "/var/run/libpod",
            "--runtime",
            "crun",
            "--storage-driver",
            "overlay",
            "--storage-opt",
            "overlay.mountopt=nodev,metacopy=on",
            "--events-backend",
            "journald",
            "container",
            "cleanup",
            "--rm",
            "74340be6f373e5febf23b28e2fb88983dc0e42dd203b1d0c3af8dba01d2e2d61"
        ],
        "Namespace": "",
        "IsInfra": false,
        "Config": {
            "Hostname": "74340be6f373",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TERM=xterm",
                "container=podman",
                "HOSTNAME=74340be6f373",
                "HOME=/root"
            ],
            "Cmd": [
                "/bin/sh"
            ],
            "Image": "docker.io/library/alpine:latest",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": "",
            "OnBuild": null,
            "Labels": null,
            "Annotations": {
                "io.container.manager": "libpod",
                "io.kubernetes.cri-o.Created": "2020-03-17T01:30:48.786055569+08:00",
                "io.kubernetes.cri-o.TTY": "true",
                "io.podman.annotations.autoremove": "TRUE",
                "io.podman.annotations.init": "FALSE",
                "io.podman.annotations.privileged": "FALSE",
                "io.podman.annotations.publish-all": "FALSE",
                "org.opencontainers.image.stopSignal": "15"
            },
            "StopSignal": 15,
            "CreateCommand": [
                "podman",
                "run",
                "--rm",
                "-ti",
                "alpine",
                "/bin/sh"
            ]
        },
        "HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "k8s-file",
                "Config": null
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": true,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [],
            "CapDrop": [],
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": [],
            "IpcMode": "",
            "Cgroup": "",
            "Cgroups": "default",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [],
            "Tmpfs": {},
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 65536000,
            "Runtime": "oci",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 1024,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 4096,
            "Ulimits": [
                {
                    "Name": "RLIMIT_NOFILE",
                    "Soft": 1048576,
                    "Hard": 1048576
                },
                {
                    "Name": "RLIMIT_NPROC",
                    "Soft": 1048576,
                    "Hard": 1048576
                }
            ],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        }
    }
]
`

**Comment by wdouglascampbell** [comment]
and here is `sudo podman info` which I see produces different output from the `podman info` I provided before.

`
sudo podman info
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  MemFree: 3395153920
  MemTotal: 4121182208
  OCIRuntime:
    name: crun
    package: crun-0.12.1-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.12.1
      commit: df5f2b2369b3d9f36d175e1183b26e5cee55dd0a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 1
  eventlogger: journald
  hostname: localhost.localdomain
  kernel: 5.5.5-200.fc31.x86_64
  os: linux
  rootless: false
  uptime: 10m 57.84s
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 12
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
`

**Comment by mheon** [comment]
`"--runtime", "crun"` from `podman inspect`

So this is properly wierd. Inspect says we're creating containers with `crun`, but the default runtime listed in `podman info` is `runc`. I'm not sure how this is.

Regardless, I think this is probably a runc vs crun change.

**Comment by wdouglascampbell** [comment]
I posted after you wrote that last comment but it seems sudo podman causes the use of crun and podman without sudo uses runc.

**Comment by wdouglascampbell** [comment]
Just to confirm what you guys are saying about "crun".

```
podman run --runtime=/usr/bin/crun --rm -ti alpine sh -c 'umask'
```
produces ```0000```.

**Comment by wdouglascampbell** [comment]
```/etc/containers/libpod.conf``` doesn't exist.

```/usr/share/containers/libpod.conf```:
```
# libpod.conf is the default configuration file for all tools using libpod to
# manage containers

# Default transport method for pulling and pushing for images
image_default_transport = "docker://"

# Paths to look for the conmon container manager binary.
# If the paths are empty or no valid path was found, then the `$PATH`
# environment variable will be used as the fallback.
conmon_path = [
            "/usr/libexec/podman/conmon",
            "/usr/local/libexec/podman/conmon",
            "/usr/local/lib/podman/conmon",
            "/usr/bin/conmon",
            "/usr/sbin/conmon",
            "/usr/local/bin/conmon",
            "/usr/local/sbin/conmon",
            "/run/current-system/sw/bin/conmon",
]

# Environment variables to pass into conmon
conmon_env_vars = [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
]

# CGroup Manager - valid values are "systemd" and "cgroupfs"
cgroup_manager = "systemd"

# Container init binary
#init_path = "/usr/libexec/podman/catatonit"

# Directory for persistent libpod files (database, etc)
# By default, this will be configured relative to where containers/storage
# stores containers
# Uncomment to change location from this default
#static_dir = "/var/lib/containers/storage/libpod"

# Directory for temporary files. Must be tmpfs (wiped after reboot)
tmp_dir = "/var/run/libpod"

# Maximum size of log files (in bytes)
# -1 is unlimited
max_log_size = -1

# Whether to use chroot instead of pivot_root in the runtime
no_pivot_root = false

# Directory containing CNI plugin configuration files
cni_config_dir = "/etc/cni/net.d/"

# Directories where the CNI plugin binaries may be located
cni_plugin_dir = [
               "/usr/libexec/cni",
               "/usr/lib/cni",
               "/usr/local/lib/cni",
               "/opt/cni/bin"
]

# Default CNI network for libpod.
# If multiple CNI network configs are present, libpod will use the network with
# the name given here for containers unless explicitly overridden.
# The default here is set to the name we set in the
# 87-podman-bridge.conflist included in the repository.
# Not setting this, or setting it to the empty string, will use normal CNI
# precedence rules for selecting between multiple networks.
cni_default_network = "podman"

# Default libpod namespace
# If libpod is joined to a namespace, it will see only containers and pods
# that were created in the same namespace, and will create new containers and
# pods in that namespace.
# The default namespace is "", which corresponds to no namespace. When no
# namespace is set, all containers and pods are visible.
#namespace = ""

# Default infra (pause) image name for pod infra containers
infra_image = "k8s.gcr.io/pause:3.1"

# Default command to run the infra container
infra_command = "/pause"

# Determines whether libpod will reserve ports on the host when they are
# forwarded to containers. When enabled, when ports are forwarded to containers,
# they are held open by conmon as long as the container is running, ensuring that
# they cannot be reused by other programs on the host. However, this can cause
# significant memory usage if a container has many ports forwarded to it.
# Disabling this can save memory.
#enable_port_reservation = true

# Default libpod support for container labeling
# label=true

# The locking mechanism to use
lock_type = "shm"

# Number of locks available for containers and pods.
# If this is changed, a lock renumber must be performed (e.g. with the
# 'podman system renumber' command).
num_locks = 2048

# Directory for libpod named volumes.
# By default, this will be configured relative to where containers/storage
# stores containers.
# Uncomment to change location from this default.
#volume_path = "/var/lib/containers/storage/volumes"

# Selects which logging mechanism to use for Podman events.  Valid values
# are `journald` or `file`.
# events_logger = "journald"

# Specify the keys sequence used to detach a container.
# Format is a single character [a-Z] or a comma separated sequence of
# `ctrl-<value>`, where `<value>` is one of:
# `a-z`, `@`, `^`, `[`, `\`, `]`, `^` or `_`
#
# detach_keys = "ctrl-p,ctrl-q"

# Default OCI runtime
runtime = "crun"

# List of the OCI runtimes that support --format=json.  When json is supported
# libpod will use it for reporting nicer errors.
runtime_supports_json = ["crun", "runc"]

# List of all the OCI runtimes that support --cgroup-manager=disable to disable
# creation of CGroups for containers.
runtime_supports_nocgroups = ["crun"]

# Paths to look for a valid OCI runtime (runc, runv, etc)
# If the paths are empty or no valid path was found, then the `$PATH`
# environment variable will be used as the fallback.
[runtimes]
runc = [
            "/usr/bin/runc",
            "/usr/sbin/runc",
            "/usr/local/bin/runc",
            "/usr/local/sbin/runc",
            "/sbin/runc",
            "/bin/runc",
            "/usr/lib/cri-o-runc/sbin/runc",
            "/run/current-system/sw/bin/runc",
]

crun = [
                "/usr/bin/crun",
                "/usr/sbin/crun",
                "/usr/local/bin/crun",
                "/usr/local/sbin/crun",
                "/sbin/crun",
                "/bin/crun",
                "/run/current-system/sw/bin/crun",
]

# Kata Containers is an OCI runtime, where containers are run inside lightweight
# Virtual Machines (VMs). Kata provides additional isolation towards the host,
# minimizing the host attack surface and mitigating the consequences of
# containers breakout.
# Please notes that Kata does not support rootless podman yet, but we can leave
# the paths below blank to let them be discovered by the $PATH environment
# variable.

# Kata Containers with the default configured VMM
kata-runtime = [
    "/usr/bin/kata-runtime",
]

# Kata Containers with the QEMU VMM
kata-qemu = [
    "/usr/bin/kata-qemu",
]

# Kata Containers with the Firecracker VMM
kata-fc = [
    "/usr/bin/kata-fc",
]

# The [runtimes] table MUST be the last thing in this file.
# (Unless another table is added)
# TOML does not provide a way to end a table other than a further table being
# defined, so every key hereafter will be part of [runtimes] and not the main
# config.
```

~/.config/containers/libpod.conf doesn't exist for either core user or root user.

It is odd to me that the default runtime in the one file is crun when that is not what rootless podman uses.

**Comment by mheon** [comment]
@vrothberg @baude Rootless should be basing its configuration for some things (runtime being among them) on root's libpod.conf, but it doesn't seem like that's happening here?

**Comment by giuseppe** [comment]
> Just to confirm what you guys are saying about "crun".
> 
> ```
> podman run --runtime=/usr/bin/crun --rm -ti alpine sh -c 'umask'
> ```
> 
> produces `0000`.

can you tell me the output for `/usr/bin/crun --version`?  Could you try crun-0.13?

**Comment by wdouglascampbell** [comment]
> can you tell me the output for `/usr/bin/crun --version`? Could you try crun-0.13?

```
$ /usr/bin/crun --version
crun version 0.12.1
commit: df5f2b2369b3d9f36d175e1183b26e5cee55dd0a
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
```

I'm not sure how to upgrade crun on Fedora CoreOS.  I will see if I can figure that out but would appreciate any direction if you have it.

**Comment by wdouglascampbell** [comment]
Just FYI.  There doesn't appear to be a way to upgrade crun on Fedora CoreOS.  Or at least I don't know how so I cannot try this with crun-0.13

**Comment by rhatdan** [comment]
@wdouglascampbell Do you still have this issue?  @dustymabe When does CoreOS get updated?

**Comment by wdouglascampbell** [comment]
> @wdouglascampbell Do you still have this issue? @dustymabe When does CoreOS get updated?

Thanks!  I just checked again and yes, this is resolved now.  It seems a recent CoreOS update deployed crun 0.13 that is indeed working.
